### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by scorreard**
Added a step by step instructions to run the pipeline

### CODE REVIEW

**Review by melsiddieg — CHANGES_REQUESTED** [review]
Hi @scorreard please add contributers section to the README with the name of the pipeline authors and their contributions

**Comment by scorreard** [comment]
@melsiddieg Great idea! 
I added the contributors names but not their description, feel free to do so. I didn't know how to appropriately define each person contribution.

**Review by melsiddieg — APPROVED** [review]

**Comment by scorreard** [comment]
@melsiddieg I noticed some layout issues that I fixed.
Please, can you review again and if it is ok for you, approve the review so that I can merge?

Thanks!

**Comment by melsiddieg** [comment]
I think the contributions are clear. I developed the SV pipeline, contributed to hail setup and script, and the migration to Nextflow DSL2. Phil contributed to testing and configuration while you and Britanny worked as a pair and should be familiar with each other contributions.

**Comment by scorreard** [comment]
I added contributions, I will run them through Phil and Brittany for approval before merging this request.

**Review by brittanyhewitson — APPROVED** [review]

**Pull request merged**
